---
inherit_gem:
  rubocop-fnando: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - vendor/**/*
    - gemfiles/**/*

Minitest/MultipleAssertions:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
